version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///data/tgupload.db
    restart: unless-stopped
